[theme]
primaryColor = "#1DB954"  # Spotify green
backgroundColor = "#121212"  # Spotify dark background
secondaryBackgroundColor = "#282828"  # Spotify dark card background
textColor = "#FFFFFF"  # White text
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false 